<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AIKernel.Abstractions" Version="$(AIKernelPackageVersion)" />
    <PackageReference Include="AIKernel.Contracts" Version="$(AIKernelPackageVersion)" />
    <PackageReference Include="AIKernel.Dtos" Version="$(AIKernelPackageVersion)" />
    <PackageReference Include="AIKernel.Enums" Version="$(AIKernelPackageVersion)" />
  </ItemGroup>
</Project>
