<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="AIKernel.Abstractions" Version="$(AIKernelPackageVersion)" />
    <PackageReference Include="AIKernel.Providers.Standard" Version="[$(AIKernelProviderPackageVersion)]" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
  </ItemGroup>
</Project>
