<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\AIKernel.Demo.Execution\AIKernel.Demo.Execution.csproj" />
    <ProjectReference Include="..\AIKernel.Demo.Replay\AIKernel.Demo.Replay.csproj" />
    <ProjectReference Include="..\AIKernel.Demo.Semantics\AIKernel.Demo.Semantics.csproj" />
  </ItemGroup>
</Project>
