<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="AIKernel.Common" Version="[$(AIKernelCorePackageVersion)]" />
    <PackageReference Include="AIKernel.Dtos" Version="$(AIKernelPackageVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AIKernel.Demo.Execution\AIKernel.Demo.Execution.csproj" />
  </ItemGroup>
</Project>
