using AIKernel.Demo.Cuda;

/// <summary>
/// [EN] Console entry point for the CUDA 13.0 teaching demo.
/// [JA] CUDA 13.0 教材デモの console entry point です。
/// </summary>
/// <remarks>
/// [EN] The runner prints either the guarded Windows dry-run log or the deterministic non-Windows skip log generated by <see cref="CudaDemo"/>.
/// [JA] この runner は <see cref="CudaDemo"/> が生成する guarded Windows dry-run log、または Windows 以外の決定論的 skip log を出力します。
/// </remarks>
public static class Program
{
    /// <summary>
    /// [EN] Runs the CUDA descriptor demo and writes each log line.
    /// [JA] CUDA descriptor demo を実行し、各ログ行を書き込みます。
    /// </summary>
    public static void Main()
    {
        foreach (var line in CudaDemo.Run())
        {
            Console.WriteLine(line);
        }
    }
}
