<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AIKernel.Core" Version="[$(AIKernelCorePackageVersion)]" />
    <PackageReference Include="AIKernel.Hosting" Version="[$(AIKernelCorePackageVersion)]" />
    <PackageReference Include="AIKernel.Kernel" Version="[$(AIKernelCorePackageVersion)]" />
    <PackageReference Include="AIKernel.Common" Version="[$(AIKernelCorePackageVersion)]" />
    <PackageReference Include="AIKernel.Abstractions" Version="$(AIKernelPackageVersion)" />
    <PackageReference Include="AIKernel.Dtos" Version="$(AIKernelPackageVersion)" />
  </ItemGroup>
</Project>
